### ISSUE TITLE
Which IDE to use?

### ISSUE THREAD

**Issue by hauke96** [paua-app/PyBalone#12]
To not have any troubles in executing code, we should all agree on _one_ IDE to rule them all.

There're some IDEs/editors we can use:
1. nano
2. vim
3. atom
4. pycharm
5. eclipse with python plugin

Please write as comment what IDE you want to use. The majority wins (otherwise there will be a battle on Friday).

I would suggest pycharm because it's rather clean (not thaaat big and slow) and has some nice features (e.g. refactoring) that other editors do not have.

**Comment by TjayG** [comment]
Which troubles ? There shouldn't be any problems or am I wrong ?

I agree with you to use Pycharme

**Comment by WalterStieben** [comment]
PyCharm looks pretty good --> I could definitely work with that one.

**Comment by hauke96** [comment]
> Which troubles ? There shouldn't be any problems or am I wrong ?

Atom does compile an empty class, pacharm does not (compiler error). Just for an example and I can imagine that there're more troubles or differences like this.

**Comment by TjayG** [comment]
Anyone against pycharme ?

**Comment by 4kobras** [comment]
I'd support PyCharm, too. Like that one.

**Comment by TjayG** [comment]
Okay. So nobody is against pycharme and almost everybody is for pycharme.

Closed
