### ISSUE TITLE
coding style

### ISSUE THREAD

**Issue by hauke96** [paua-app/PyBalone#2]
Here some ideas for our coding style, feel free to comment on them:
# Coding style
## Naming convention

Names begin with a lower case letter and are written in camel-case, meaning every subword begins with a upper case letter, e.g. `calculateAbsolutePlayerPosition()`.
## Private fields in classes

There is the single-underscore-way of creating non-public members, but thats a rather weak one and is mainly used on imports. We use the strong one with two underscores (e.g. `__playerPosition`) that implements a private member of a class.
## Documentation

To create comments we use [`PEP 257`](https://www.python.org/dev/peps/pep-0257/) to write documentation comments, so something like this:<br>

``` python
def setBackgroundColor(self, color):
  """
  Sets the new background color and directly applies it to the surface.
  Arguments:
  color -- The new color of the window.
  """
```

**Comment by 4kobras** [comment]
I quote my Python book on private members: "we are all consenting adults here". It is unusual to hide many things in a Python project.
However CamelCase is a fine way to name stuff, so I agree on that.

**Comment by hauke96** [comment]
Walter, Tjorben, and I (Hauke) decided to use private members with getter/setter methods and not public ones due to a consistent state of objects.

**Comment by 4kobras** [comment]
Since this seems to be a majority decision I will comply
