### ISSUE TITLE
German vor englisch?

### ISSUE THREAD

**Issue by hauke96** [paua-app/PyBalone#3]
Ich denk für den code ist englisch besser (also kommentare, Variablennamen etc.) wie ists mit commits oder issues und so? Englisch oder deutsch (momentan ist das ja durcheinander)? Ich ware für englisch, dann ich es einheitlich.

**Comment by 4kobras** [comment]
ich mag englisch lieber :P

**Comment by hauke96** [comment]
Englisch beschlossen auf Versammlung :D
