### ISSUE TITLE
UIs in pygame

### ISSUE THREAD

**Issue by hauke96** [paua-app/PyBalone#6]
Do some research about UIs in pygame (are there any libraries? native functions? ...) until 13.5.

**Comment by 4kobras** [comment]
Jack-of-all-Trades: Kivy.
----Platforms: Linux, Windows, MacOS X, iOS, Android
----Use: GUI with Multitouch support und integrated virtual keyboard
----Notes: OpenGL-Derivat
Desktop-Master: PyFltk
----Platforms: Windows, Unix, MacOS X
----Use: lightweight, modular UI with 3D support 
----Notes: Wrapper for C++ FLTK OpenGL Framework
Other: Jython/Cython
----Platforms: most
----Use: --
----Notes: Technically not a UI framework, Jython/Cython allow for implementation of Python modules within a Java or C project and thus using their UI frameworks

**Comment by hauke96** [comment]
The problem is that these frameworks/libraries do not use Pygame and therefore we can't use them. There're libraries for Pygame but we maybe implement our own UI package.

**Comment by TjayG** [comment]
Its decided. We create our own UI package and use Pygame for help
