### ISSUE TITLE
Abbreviation Glossary

### ISSUE THREAD

**Issue by 4kobras** [paua-app/PyBalone#7]
Some words are long to type and often to use.
As such I propose the introduction of an open glossary to introduce abbrevations which then can be used both in GitHub features and in source code.

Possible Entries could be:
fw:Framework
mm:Magic Method
et al

**Comment by TjayG** [comment]
For me i won't use any abbrevations, but this is an individual capacity

**Comment by TjayG** [comment]
And most of your abbrevations will understand by people without a glossary

**Comment by hauke96** [comment]
I won't use them either due to autocompletion and the capability of fast writing ;)
Nevertheless the abbreviation of common words/phrases like "user interface" into "UI" is quite useful.

I think that a glossary with word which have an uncommon abbreviation is a bit too much.

**Comment by TjayG** [comment]
Decided on 13.05.2016  (Hauke, Walter, Jan, Tjorben). 
Solution: We don't need a glossary
